filter:
    paths: [library/*]
    excluded_paths: [vendor/*, tests/*, docs/*]

before_commands:
    - "composer self-update && composer --version"
    - "composer install --dev --prefer-source"

tools:
    external_code_coverage: true
    php_code_sniffer:
        enabled: true
        command: vendor/bin/phpcs
        config:
            standard: PSR2
        filter:
            paths: ["library"]
    php_cpd:
        enabled: true
        command: vendor/bin/phpcpd
        excluded_dirs: ["docs", "tests", "vendor"]
    php_cs_fixer:
        enabled: true
        command: vendor/bin/php-cs-fixer
        config:
            level: all
        filter:
            paths: ["library"]
    php_loc:
        enabled: true
        command: vendor/bin/phploc
        excluded_dirs: ["docs", "tests", "vendor"]
    php_mess_detector:
        enabled: true
        command: vendor/bin/phpmd
        config:
            ruleset: phpmd.xml
        filter:
            paths: ["library"]
    php_pdepend:
        enabled: true
        command: vendor/bin/pdepend
        excluded_dirs: ["docs", "tests", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["library/*"]
    sensiolabs_security_checker: true