language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
 - composer install --dev

before_script:
 - cd tests

script:
 - vendor/phpunit/phpunit/phpunit.php -c tests/phpunit.xml

notifications:
  email: false
