language: php

php:
  - 5.3.3
  - 5.4
  - 5.5


install:
  - composer self-update && composer --version
  - composer install --dev --prefer-source

before_script:
  - tests/travis/sphinx-setup.sh

script:
 - vendor/bin/phpunit -c tests/

notifications:
  email: false
