language: php

php:
  - 5.3.3
  - 5.4
  - 5.5

branches:
  only:
    - master

install:
  - composer self-update && composer --version
  - composer install --dev --prefer-source

before_script:
  - tests/travis/sphinx-setup.sh

script:
 - vendor/bin/phpunit -c tests/
 - vendor/bin/phpunit -c tests/ --group=integration

notifications:
  email: false
